#pragma once

#undef glColor
#undef detectCollision
#undef updatePosition
#undef updateVelocity
#undef getGravity
#undef getAltitude
#undef getTime
#undef EARTH_SPEED
#undef calculateEarthSpeed
#undef computeDistance
#undef random
#undef Star
#undef Fragment
#undef PartType
#undef Part
#undef Projectile
#undef DreamChaser
#undef Starlink
#undef Dragon
#undef Hubble
#undef Sputnik
#undef GPS
#undef Satellite
#undef OrbitalObject
#undef ogstreamFake
#undef ogstreamDummy
#undef ogstream
#undef PT
#undef Angle
#undef Acceleration
#undef Velocity
#undef Position
